### ISSUE TITLE
Skills and talent advance

### ISSUE THREAD

**Issue by Doc501** [fmasa/wfrp-master#147]
Issue with advancing and adding more points to skills and talents. Cant add more than 1 advance without leaving and entering skill again, samé with talents. Advancing also not visible without leaving the skill/talent.

**Comment by fmasa** [comment]
This is already fixed in master (https://github.com/fmasa/wfrp-master/pull/144). I'll tag a new release in a few hours.

**Comment by Doc501** [comment]
I see now. I just confused items with trappings, I thought it's a same thing. English is not my native language. Thanks.

**Comment by fmasa** [comment]
The [3.13.0](https://github.com/fmasa/wfrp-master/releases/tag/3.13.0) was released.
