### ISSUE TITLE
Missing Save Button in Calendar

### ISSUE THREAD

**Issue by Doc501** [fmasa/wfrp-master#163]
Save button si missing in months with "additional" days (Hexentag, Mitterfruhl, Sonnstill, Geheimbstag, Mittherbst and Mondstille). Now I see it is happening just in one of my two parties for some reason.
![Screenshot_2023-08-26-13-49-01-485_cz frantisekmasa dnd](https://github.com/fmasa/wfrp-master/assets/112588712/bf915687-bb23-4cde-bb4d-a85c001f6c8c)

**Comment by fmasa** [comment]
Thanks for report, this will be fixed in 3.14.0
