### ISSUE TITLE
French language

### ISSUE THREAD

**Issue by TheoKDK** [fmasa/wfrp-master#171]
Hi, I saw that it was possible to translate via Weblate, so I translated all the channels into French. I was wondering what I could do now to get the application in French? This would allow me to check that the translations are correct and in the right place.

I'd like to take this opportunity to ask whether it will be possible in future to import a pdf of the basic book in another language?

Thank you :)

**Comment by fmasa** [comment]
@TheoKDK Hi, thank you for the translations. 

>  I was wondering what I could do now to get the application in French? This would allow me to check that the translations are correct and in the right place.

I'm working on getting the automatic beta releases to work. Then you would be able to opt-in on Google Play to beta releases and you will be able to see changes available in the current `master` branch (the main branch, where your translations are after I accept the PR with them). I'll document all that and will let you know here once it's ready :slightly_smiling_face:

> I'd like to take this opportunity to ask whether it will be possible in future to import a pdf of the basic book in another language?

I don't plan to add support for this. The PDF import is clunky and takes a significant time to maintain as it is and most of the code cannot likely be reused for other languages.
I think the best way is for someone to develop this outside the app (that someone can certainly copy the base code from this app) for now and export everything in JSON (the app supports custom imports in JSON format).
I'm willing to accept PRs with support for additional languages if someone can contribute sufficiently tested code that would not add too much complexity.

**Comment by TheoKDK** [comment]
Thanks for your reply
If I understand correctly, is there access to a beta version of the app? Or a future one?

Yes, I understand that it's complicated to implement, but I was just asking just in case, to make my job easier (I only use the app as a player, so I don't need all the elements, I'll just have to create them as needed).

**Comment by fmasa** [comment]
> If I understand correctly, is there access to a beta version of the app? Or a future one?

@TheoKDK Got it to work - you can join beta here: https://play.google.com/apps/testing/cz.frantisekmasa.dnd

**Comment by fmasa** [comment]
@TheoKDK I would like to tag a new release this week. Would you have time to check the translations before the weekend, or should I postpone (hide the French language in the app for now)? :slightly_smiling_face:

**Comment by TheoKDK** [comment]
I'll try to do that today and tomorrow, otherwise we'll have to postpone.

Thanks for the link :)

**Comment by TheoKDK** [comment]
In the end I was able to have a look at it, I did make a few changes and it seems to be working better.
But is it possible to modify the short version of the characteristics? The one in the first tab?

Thanks

**Comment by fmasa** [comment]
Thank you for the additional translations. Is there anything else you plan to look at, or is it good to go? :slightly_smiling_face:

**Comment by TheoKDK** [comment]
I made a few final changes today, but I think it's fine as it is.
If in the future I see something to change I'll make the change and pass the information on to you.

**Comment by fmasa** [comment]
@TheoKDK Thank you very much for all the good work! I'm closing this issue now as done. If anything comes up, feel free to either mention me (@fmasa) here or create a new issue.
