### ISSUE TITLE
Change Avatar bug? and zoom on Avatar 

### ISSUE THREAD

**Issue by Stilzkin** [fmasa/wfrp-master#188]
Hi! I dont know if is only my problem, but now when i go to change avatar the app crash when in gallery :(

In the future, will it be possible to enlarge the image by tapping on the avatar image? Thanks!

**Comment by fmasa** [comment]
I added a new issue https://github.com/fmasa/wfrp-master/issues/191 for the feature request. As for the bug, I fixed this in https://github.com/fmasa/wfrp-master/pull/190 and I will release a new version with this fix today.
