### ISSUE TITLE
Well-being

### ISSUE THREAD

**Issue by Doc501** [fmasa/wfrp-master#19]
Add Critical Wounds, Injuries and Diseases to Well-being tab. Would be nice if Critical Wounds somehow lock the max Wounds until the Injuries are removed.

**Comment by fmasa** [comment]
> Would be nice if Critical Wounds somehow lock the max Wounds until the Injuries are removed.

Could you elaborate on how that might work? Also, do you mean special rules for Amputation or is there a rule I'm not aware of?

**Comment by Doc501** [comment]
Rule for healing Critical Wounds says "Critical Wounds do not 
count as healed until all conditions they inflict are removed." So what i ment is something like when i add a Critical Wound to a Player, Theyr max Wounds would be lockt. Like 15/16 and canot be 16/16 until a Critical Wound would be removed.

**Comment by Doc501** [comment]
For the rest would be nice some tab like trappings for example .Box for a name, be able chose if its a Injuri (maybe even if its broken bone or torn muscle), diesiese or infection (in this cases a box for duration), mutation (physival/mental) or amputation and some box for notes.

**Comment by fmasa** [comment]
The only case IMO when Character cannot heal one Wound is when they have an Amputation that wasn't resolved by Surgery yet (Surgery, page 181).

**Comment by Doc501** [comment]
sorry then, i misunderstand that part

**Comment by fmasa** [comment]
No problem, I need to re-read this section every few weeks when I forget, since it's so poorly written :grinning: 

---

Anyway, I really like the rest of the feature and I think that this will be great addition!

**Comment by Doc501** [comment]
with the new trapping type (prosthetics) it would be nice to have the injuries/amputations added as well

**Comment by fmasa** [comment]
> with the new trapping type (prosthetics) it would be nice to have the injuries/amputations added as well

@Doc501 I still plan to do that sometime in the future (we are probably talking several months, as there are other features I plan to introduce and my time is limited right now :slightly_smiling_face:). I added Prosthetics mainly because I'm finishing Trappings import from Core Rulebook and I noticed, that Prosthetics were by mistake missing from the app.

**Comment by fmasa** [comment]
There is new Wellbeing tab that will land in 3.18.0. It contains Diseases and Corruption tracker, I plan to add Injuries and Mutations as well.

I'm closing this in favor of https://github.com/fmasa/wfrp-master/issues/316 and https://github.com/fmasa/wfrp-master/issues/315. :slightly_smiling_face:
