### ISSUE TITLE
Effects and Auto Wounds working with Translations

### ISSUE THREAD

**Issue by Stilzkin** [fmasa/wfrp-master#195]
As title says, the Effects feature work with translations?

Thanks!

**Comment by fmasa** [comment]
It does not work. But I can certainly make it work. For this, I think we should introduce a language picker for the whole Party as well to make it independent of language used by specific users. With this approach users with English localization would have the same logic as other users when applying effects in the context of the Italian Party, etc.

**Comment by fmasa** [comment]
This is now working for both Italian and French, which are currently supported in the language chooser and will be released in 3.15.0
