### ISSUE TITLE
Quantity for Compedium Trappings 

### ISSUE THREAD

**Issue by Doc501** [fmasa/wfrp-master#212]
Not able to set a Quantity on the Trappings from the Compedium. It realy messing up the inventory management a little bit. Especillay with things like throwing weapons, rations, potions, scrolls etc.

**Comment by Doc501** [comment]
Oh, sorry, now I can see it. My players still hlave in inventory custom trappings, so i got them mixed up. I was in impression that just custom trappings have that. My bad, but yes, for throwing weapons, would be nice to have that too. (I realy need to test out every possibility before in post an issiue)

**Comment by Doc501** [comment]
I also thought that it would be nice if trappings had a notes tab for players, so that they could write down e.g. where they found them, if the weapon is dipped in poison, or if it was a scroll, what kind of spell is on it.

**Comment by fmasa** [comment]
I added https://github.com/fmasa/wfrp-master/issues/220 for Player notes and the Quantity can now be changed for all the Trappings.
