### ISSUE TITLE
Unable to Import Core Rulebook (English)

### ISSUE THREAD

**Issue by RyzenNesmir** [fmasa/wfrp-master#234]
**Describe the bug**
When I try to import my PDF copy of the core Rulebook, I get an error.

"PDF import failed. Check that you provided a valid rulebook PDF"

The PDF is the English version of the Core Rulebook that came with my physical copy when I purchased it. I already reached out to frantisekmasa1@gmail.com and he directed me here, as he was unable to replicate the issue.

**To Reproduce**
1. Go to 'Compendium'
2. Click on 'Import from Rulebook' under 3 dot menu
3. Click on "Core Rulebook"
4. Scroll down to Core Rulebook.pdf
5. See error: PDF import failed. Check that you provided a valid rulebook PDF

**Expected behavior**
Expected to import information from core Rulebook into the application

**Screenshots**

![Screenshot_20231221-205505](https://github.com/fmasa/wfrp-master/assets/154570610/c1592d77-267e-4457-8764-99c81f6b1bb7)

![Screenshot_20231221-205537](https://github.com/fmasa/wfrp-master/assets/154570610/db0ebf7b-be02-4cda-8f0b-d453f8617433)

![Screenshot_20231221-205621](https://github.com/fmasa/wfrp-master/assets/154570610/77d3891b-00fd-4a30-a209-e9ee03c00eba)

**Smartphone (please complete the following information):**
 - Device: Google Pixel 7a
 - Android version: 14
 - Device language English
 - App version dev-765796a
 - App language English

**Additional context**

**Comment by fmasa** [comment]
Hi @RyzenNesmir,
can you make sure that you are using the latest version of Core Rulebook?
The versioning of Cubicle 7's PDFs is a bit messy. For CRB the latest version of the rulebook ends with `version4.pdf`.

If this is not a problem, we can debug this more.
I plan to add "Common issues" section to WIKI around Rulebook imports and also improve error collecting (so it's easier to catch these bugs).

**Comment by fmasa** [comment]
Closing as stale.

@RyzenNesmir Let me know if this is still a problem and we can reopen this.
