### ISSUE TITLE
Additional notes overwritten by Motivation

### ISSUE THREAD

**Issue by Odoamar** [fmasa/wfrp-master#248]
Editing Motivation from NOTES tab in Characters section overwritten Additional Notes info. 

1. Select Character
2. Go to NOTES
3. Click on Edit Motivation
4. Save it
5. Additional Notes are overwritten by this edit action

**Expected behavior**
Independent edit action 

 - Device: MIUI Global 12.5.6, model M2003J15SG (Redmi Note 9)
 - Android version: 11 RP1A.200720.011
 - Device language: English
 - App version: 3.15.3
 - App language: English

**Additional context**
An easy workaround is available, User can do it from Edit Character: Basics.

**Comment by fmasa** [comment]
Fixed!
