### ISSUE TITLE
App crash after NPC duplication 

### ISSUE THREAD

**Issue by Odoamar** [fmasa/wfrp-master#253]
**Describe the bug**
App crash when I duplicate NPC with Imported Basic skills. 

**To Reproduce**
1. Go to NPCs
2. Select any existing NPC or create new NPC
3. Go to "Skills & Talents" tab
4. Press 3dots and select Import Basic Skills
5. Go back to NPC list
6. Hold press on this NPC
7. Select duplicate
8. App crash

**Expected behavior**
Duplicate should work as intended. 

**Smartphone (please complete the following information):**
Device: MIUI Global 12.5.6, model M2003J15SG (Redmi Note 9)
Android version: 11 RP1A.200720.011
Device language: English
App version: 3.15.4
App language: English

**Comment by fmasa** [comment]
Reproduced, I will try to fix this tomorrow. Thanks for a report!
