### ISSUE TITLE
Make Talent "Max" & "Tests" Visible to Players...

### ISSUE THREAD

**Issue by ChapterGrim** [fmasa/wfrp-master#257]
At the moment, the "Max" and "Tests" elements of Talent Format are not player facing, and are thus not visible to players who ultimately need that information, it's also not visible to GMs within "character sheets" - only via the app's compendium...

**Comment by fmasa** [comment]
Hi @ChapterGrim,
I checked and I do see **Tests** line in Character sheet 🤔 But I do not see the **Max**, which I agree should be added to the Talent detail in Character sheet as well.

**Comment by ChapterGrim** [comment]
Not sure why but I don't... 🤔

![Screenshot_20240309_175819_WFRP Master](https://github.com/fmasa/wfrp-master/assets/25955705/8e5e04c1-3fad-40c8-8e29-d1ab44b637c6)

**Comment by ChapterGrim** [comment]
I'm not the GM in that game, but I went into a campaign I GM and I could see, but the GM in the GM above sent the following...

![Uploading Messenger_creation_519161bf-0e2d-4399-b054-60b8c9a071bd.jpeg…]()

**Comment by ChapterGrim** [comment]
I'm not the GM in that game, but I went into a campaign I GM and I could see, but the GM in the GM above sent the following...

![Messenger_creation_519161bf-0e2d-4399-b054-60b8c9a071bd](https://github.com/fmasa/wfrp-master/assets/25955705/2912f45e-8b73-4be6-b257-4813830b6a08)

**Comment by ChapterGrim** [comment]
It turns out our collaborative compendium has all the "Tests" boxes blank, I'm guessing because it predates the "Tests" box or something... 🤣

**Comment by fmasa** [comment]
@ChapterGrim I haven't even considered that. `Tests` field was introduced bit later than other Talent fields. 😅

You (or your GM) can reimport the rulebook and this will automatically be added everywhere (I recommend to export your compendiums as a backup, in case you made some changes you don't want to lose) 🙂

**Comment by ChapterGrim** [comment]
Cheers! Hopefully making the `Max` field player facing isn't difficult... 🙂

**Comment by fmasa** [comment]
This will take some work, but it makes sense to add it. I'll try to get this to the very next version 🙂
