### ISSUE TITLE
Clickable conditions

### ISSUE THREAD

**Issue by Thewalls99** [fmasa/wfrp-master#306]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Currently you can assign conditions to a player (Ex Ablaze, stunned, etc) but there is no information presented on the conditions. It would be nice if we could click/tap on the name of the condition to get more information on how it affects the character. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by fmasa** [comment]
H @Thewalls99, thanks for getting in touch 🙂 

I'm actually working on this right now and I expect that this will land in next version 🙂

You will be able to import some rules as Journal entries [using the Rulebook PDF import](https://github.com/fmasa/wfrp-master/wiki/Creating-a-Party#importing-compendium) and clicking the condition will automatically get you to this imported rule.

**Comment by fmasa** [comment]
@Thewalls99 This is now implemented in beta version and will be released in a few days.

**Comment by Thewalls99** [comment]
Awesome! Thanks so much!
  

  

  

  
  
  
  
  
>
