### ISSUE TITLE
New field on characters abd/or parties for general notes

### ISSUE THREAD

**Issue by ccthiel** [fmasa/wfrp-master#36]
Would be great to have a field you can add whatever notes you want to for characters or parties

**Comment by fmasa** [comment]
Hi, do you mean GM-only notes or public notes visible to Characters?

There is already a field called "Additional notes" for Character.

GM-only Character notes are tracked in #35

**Comment by ccthiel** [comment]
I see the additional notes section for characters but can't seem to do anything with it

**Comment by ccthiel** [comment]
I just thought Additional Notes was a header for the page.  Doesn't seem to be any way to actually add Notes under that section

**Comment by fmasa** [comment]
Additional Notes can be changed by clicking the pencil in top-right corner and then in the `Basics` section, but I recognize that it's poor UX.

I will think of some more obvious ways to let users change the notes. :thinking:

**Comment by ccthiel** [comment]
Aaah yeah I failed to spot that.  Thanks!

**Comment by fmasa** [comment]
As I said, I think that the UX is not great, so no worries! I'll try to address that.

For Party notes I created https://github.com/fmasa/wfrp-master/issues/39
