### ISSUE TITLE
No "Tests" in Talents

### ISSUE THREAD

**Issue by ChapterGrim** [fmasa/wfrp-master#368]
For some reason, the "Tests" line in Talents isn't carried over in an Exported or Imported Compendium - it's unclear which it is...

**Comment by fmasa** [comment]
Hi @ChapterGrim,
thanks for report! I see the problem is in the import. I have fix ready in #369. I will merge it and tag a new version right away.

**Comment by fmasa** [comment]
@ChapterGrim I tagged the [3.20.1](https://github.com/fmasa/wfrp-master/releases/tag/3.20.1), so this should be available in Play store in hour or so.
