### ISSUE TITLE
Up in Arms, Winds of Magic Talent and skils

### ISSUE THREAD

**Issue by LoGan-Grey-One** [fmasa/wfrp-master#38]
Importing Pdfs of those rulebooks makes app crash.
Afer relaunch of App there is no talents or skills from those books.

**Comment by fmasa** [comment]
Hi,
currently, only the Core rulebook is supported. Which version do you encounter the crash on? 

I plan to add support for:

- Talent imports from Up in Arms
- Talent imports from Winds of Magic
- Spell imports from Blood & Bramble
- Spell imports from WFRP: Sullasara's Spells of Unrivalled Utility

What I currently don't plan to add support for:

- Career imports from either of these books

**Comment by LoGan-Grey-One** [comment]
Crash happend when i try import up in arms or winds of magic. Corebook imported just fine.

**Comment by fmasa** [comment]
I ask because since https://github.com/fmasa/wfrp-master/pull/28 (released in 3.5.0), PDF import should never crash the app.

**Comment by SimonasBanys** [comment]
is there any reason why career imports from those books arent planned?

**Comment by fmasa** [comment]
> is there any reason why career imports from those books arent planned?

Primarily due to different internal representations (slightly different font sizes and layouts of paragraphs in WoM/UiA) in the PDF. This means that this would need separate implementation for UiA and WoM.
This would require quite a lot of time that can be spent elsewhere.

So I don't say that this will never happen, but currently there are IMO more useful features to implement :slightly_smiling_face:

**Comment by SimonasBanys** [comment]
> > is there any reason why career imports from those books arent planned?
> 
> Primarily due to different internal representations (slightly different font sizes and layouts of paragraphs in WoM/UiA) in the PDF. This means that this would need separate implementation for UiA and WoM. This would require quite a lot of time that can be spent elsewhere.
> 
> So I don't say that this will never happen, but currently there are IMO more useful features to implement 🙂

does this apply to how career is represented as well? since the description is less important for character sheet management

**Comment by fmasa** [comment]
> does this apply to how career is represented as well? since the description is less important for character sheet management

@SimonasBanys Ha! I managed to parse the careers from Winds of Magic and Up in Arms. I'll check a few other supplements (as this new approach should mean fairly low-effort support for additional books) and if everything works out. This should be available in versions not far from now :slightly_smiling_face:

**Comment by SimonasBanys** [comment]
that is fantastic news! would those include spells as well? as I am planning adventure in the future where the whole party is wizards 😄 and trying to minimise the complications with character management as much as possible

**Comment by fmasa** [comment]
Yes, current plan is:

- Winds of Magic careers (got this to work)
- Up in Arms careers (got this to work)
- Up in Arms talents
- Winds of Magic spells (probably without rituals as this would require additional fields on top of the current Spell model)

**Comment by fmasa** [comment]
This was now released as part of [3.8.0](https://github.com/fmasa/wfrp-master/releases/tag/3.8.0)
