### ISSUE TITLE
Traits and Careers are not imported on devices with non-English locale

### ISSUE THREAD

**Issue by Doc501** [fmasa/wfrp-master#41]
It seems the new compediums not working for me. If I import a PDF of a Core book that adds nothing new. All of the traits i add manually but i dont really like do the same with careers.

**Comment by fmasa** [comment]
This is strange.

Do you see the list of Traits and Careers in the *Importing Rulebook* screen (like on the screenshot below)? Or are these items missing even during import?

![image](https://user-images.githubusercontent.com/5658260/201749069-a04285a7-77cb-459a-af4a-7face4909f09.png)

**Comment by Doc501** [comment]
No, i dont see nothing to select. Its just empty space.

**Comment by Doc501** [comment]
![Screenshot_2022-11-14-22-18-48-948_cz frantisekmasa dnd](https://user-images.githubusercontent.com/112588712/201767604-e144fa19-bbec-4919-98c4-ca9bf1d937cf.jpg)
![Screenshot_2022-11-14-22-18-41-168_cz frantisekmasa dnd](https://user-images.githubusercontent.com/112588712/201767612-34241716-7dd5-43c1-811b-35eaac701d32.jpg)

**Comment by Doc501** [comment]
I have a PDF from a Humble Bundle, everything other work just fine. I using a Redmi 9 phone.

**Comment by fmasa** [comment]
Ha! This seems to be locale-specific. That explains why it works when using English as a system language, but it breaks for when user has different system language (such as Czech).

@Doc501 I'll try to pinpoint the specific issue and come up with a fix. I know this is an awkward solution, but temporarily changing the OS language a restarting the app should let you import everything in the meantime.

**Comment by Doc501** [comment]
@fmasa thanks, that works, you saved me lot of copy/paste time.

**Comment by Joly0** [comment]
Just wanted to say, that i have the same issue (my locale is german) and i was able to fix this aswell by changing the system language to english. Still curious, why all other parts are imported correctly, but the traits and careers arent? Is there something different in the logic there?

**Comment by fmasa** [comment]
> Still curious, why all other parts are imported correctly, but the traits and careers arent? Is there something different in the logic there?

Yes, the logic is quite different. All the previous compendiums are imported using custom grammar - only text is extracted from the PDF (see [SpellListGrammar](https://github.com/fmasa/wfrp-master/blob/711120ba34a0020c2e1824b4adca7ddcf2fac6f1/common/src/commonMain/kotlin/cz/frantisekmasa/wfrp_master/common/compendium/domain/importer/grammars/SpellListGrammar.kt) for example.

Traits are Careers are extracted with some metadata that makes it easier to do the parsing - we can distinguish between headings, bold text etc. (see [RulebookTraitImporter](
https://github.com/fmasa/wfrp-master/blob/711120ba34a0020c2e1824b4adca7ddcf2fac6f1/common/src/commonMain/kotlin/cz/frantisekmasa/wfrp_master/common/compendium/domain/importer/RulebookTraitImporter.kt) for example).

I would like to unify the approach across the compendiums. The main motivation for different approach was that it was easier to implement. And I'm still not sure which approach is better, but the latter one is certainly buggy.

**Comment by Joly0** [comment]
> I would like to unify the approach across the compendiums. The main motivation for different approach was that it was easier to implement. And I'm still not sure which approach is better, but the latter one is certainly buggy (there is probably some String function use somewhere that uses current locale).

Ah, interesting. Makes totally sense. Just another question then, regarding my other open feature request https://github.com/fmasa/wfrp-master/issues/24 Would it be possible then in the future maybe, to import Rulebooks from other languages (German in my case)?

**Comment by fmasa** [comment]
I currently don't plan that. English Rulebook import already takes a significant portion of development time.

But the app supports JSON import/export which could be a better way to import stuff if you can somehow manage to extract this from the rulebook yourself. If you wan't to talk more about this, le's move this to [Discussions](https://github.com/fmasa/wfrp-master/discussions) please :slightly_smiling_face:
