### ISSUE TITLE
App crash (WFRP majster)

### ISSUE THREAD

**Issue by Doc501** [fmasa/wfrp-master#6]
Hi, after last update i cant open my existung Party. When i try to open it the app just crash.

**Comment by fmasa** [comment]
Hi, sorry for the bug. Can you tell me the name of the Party, so I can investigate?

**Comment by Doc501** [comment]
Enemy in Shadows (RGB)

**Comment by fmasa** [comment]
This is now fixed in 3.3.1 which should be out in a few hours. Can you update and let me know whether everything works for you?

Thank you for the report and sorry for the issues again.

**Comment by Doc501** [comment]
Now the app crashes when i try to remove Hardy talent from the character who already hlave it.

**Comment by fmasa** [comment]
I created https://github.com/fmasa/wfrp-master/issues/10, to track this separately. I think I may know the culprit as well.
